title: "Wael Fahmy"
description: "Full Stack Engineer | AI/ML | Cybersecurity"
author: "Wael Fahmy"
theme: jekyll-theme-minimal
logo: /assets/img/avatar.png
show_downloads: false
google_analytics: false
